apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-gpg-keys-cm.yml
  - argocd.yml
  - bootstrap-application.yml
  - argocd-clusterrolebinding.yml
